# Generated by Django 2.1.7 on 2019-05-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Home DIY', 'Home DIY'), ('Electronics', 'Electronics'), ('Schools', 'Schools'), ('Visas', 'Visas'), ('Restaraunts', 'Restaraunts'), ('Noodles', 'Noodles')], default=('General', 'General'), max_length=100),
        ),
    ]
