# Generated by Django 2.1.7 on 2019-04-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
