# Generated by Django 2.1.7 on 2019-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20190430_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shopcategory',
            field=models.CharField(choices=[('Home', 'Home'), ('Electronics', 'Electronics'), ('Schools', 'Schools'), ('Noodles', 'Noodles')], max_length=100),
        ),
    ]
