# Generated by Django 2.1.7 on 2019-05-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20190430_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shopcategory',
            new_name='category',
        ),
    ]
