# Generated by Django 2.1.7 on 2019-05-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20190501_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Home DIY', 'Home DIY'), ('Electronics', 'Electronics'), ('Schools', 'Schools'), ('Restaraunts', 'Restaraunts'), ('Noodles', 'Noodles')], max_length=100),
        ),
    ]
